### ISSUE TITLE
All emails through Google Workspace are coming from me (even with sender address changed)

### ISSUE THREAD

**Issue by Joalrdexan** [gophish/gophish#2583]
What version of Gophish are you using?: 0.12.0

Brief description of the issue: With all my senders being set to other addresses I have SMTP set to my own Google Workspace account for authentication and any emails I send to show my email as the from address. In the headers, I can see the email I want (Shown below)
I also don't seem to be able to add any Custom X-headers either. The red button to add - simply does nothing :( 

What are you expecting to see happen? : Email to be received from a fake email (to simulate spoofing)

What are you seeing happen? Emails received by me

Message headers (with redacted email for myself)

```
Return-Path: <MY-EMAIL>
Received: from gophish (57.22.88.34.bc.googleusercontent.com. [34.88.22.57])
        by smtp.gmail.com with ESMTPSA id w1-20020a05651234c100b0049472efaf7asm204302lfr.244.2022.09.02.03.57.50
        for <MY-EMAIL>
        (version=TLS1_3 cipher=TLS_AES_128_GCM_SHA256 bits=128/128);
        Fri, 02 Sep 2022 03:57:51 -0700 (PDT)
From: MY-EMAIL
X-Google-Original-From: noreply@google.authentlcation.com
Mime-Version: 1.0
Date: Fri, 02 Sep 2022 10:57:51 +0000
X-Mailer: gophish
Message-Id: <1662116270436350189.6841.2951843639925513193@gophish>
Subject: Create your new password now
To: Jordan Newton <MY-EMAIL>
Content-Type: text/html; charset=UTF-8
Content-Transfer-Encoding: quoted-printable
```

Any help would be appreciated.

**Comment by M-Joslyn** [comment]
I've having the same issue. I've tried changing the SMTP to those suggested in this thread: https://github.com/gophish/gophish/issues/182 but using those results in errors and I can't send test emails.

**Comment by Joalrdexan** [comment]
> I've having the same issue. I've tried changing the SMTP to those suggested in this thread: #182 but using those results in errors and I can't send test emails.

that is a very very old thread. Likely no longer valid due to the changes/updates

**Comment by glennzw** [comment]
Hi @Joalrdexan - thanks for reaching out. There was a problem adding custom headers which has been fixed in the source version, but I haven't pushed it to the binary releases yet. So if you're able to compile from source that should allow you to add custom headers.

You can also set the Sender Envelope in the Email Template:

![Screenshot 2022-09-09 at 08 56 13](https://user-images.githubusercontent.com/3966613/189301160-c5e5b4e5-e724-4f4a-9cca-2a9667c7abb5.png)

I hope that helps.

**Comment by joannahsu11** [comment]
im having the same issue. setting the sender envelope gave the same result :(

**Comment by glennzw** [comment]
If possible would you all be able to try reproduce this in gophish v0.11 ? We added Sender Envelope support then, and I'd like to try and isolate if that's causing issues.

**Comment by joannahsu11** [comment]
In v0.11, even though I did this:
![Screenshot 2022-11-14 114409](https://user-images.githubusercontent.com/72953248/201751327-9ce69897-ea6a-4bb2-8c6b-9b2a2e469eab.png)

the receiver can still see my real email:
![Screenshot 2022-11-14 114652](https://user-images.githubusercontent.com/72953248/201752173-7127fab3-a8a5-4cf6-9b14-e9129c39b629.png)

**Comment by glennzw** [comment]
So I think this is an artefact of Google Workspace, it won't let you override the sender address.

**Comment by glennzw** [comment]
Haven't heard back so closing out. Feel free to reopen.
