### ISSUE TITLE
Different timezones in web browser and server cause campaign to not start

### ISSUE THREAD

**Issue by tyrells** [gophish/gophish#316]
Good day,

I am busy working with the latest version of gophish (checked out from the github repo) and noticed a bug. When you set up a new campaign, if the browser is working in a different timezone to the server, the campaign does not begin correctly.

Kind regards,

**Comment by jordan-wright** [comment]
Interesting! Let me see if I can find time to debug this and implement a fix.

Thanks for the report!

**Comment by ustayready** [comment]
Same problem here, looks like when you set a future date on a campaign, it's not taking into consideration the AM/PM. I created a campaign in the future using 11PM UTC time but when I checked the database entry, it inserted 2016-08-16 11:00:00-04:00 instead of 2016-08-16 23:00:00-04:00 so the date looked past tense and kicked off immediately. This breaks larger campaigns because the results table doesn't have time to get populated before the processCampaign() function kicks off, whatever entries are available is all that gets processed. :)

**Comment by jordan-wright** [comment]
Working on a fix for this. The trick is making sure that:

* moment.js is working as expected
* golang's `time` is working as expected
* conversion from sqlite to golang's `time` is working as expected

Quite a few moving parts - I'll update when I have more info

**Comment by jordan-wright** [comment]
Ok, I've pushed out a fix targeting the AM/PM issue, but I think it may cover the timezone issue as well (since that may just be masking the AM/PM issue).

Let me know if that works for you @ustayready and @tyrells

**Comment by ustayready** [comment]
I can confirm the AM/PM issue resolved everything! I successfully created a campaign 5 minutes in the future and verified the created_date / launch_date in sqlite. Everything looks great! Nice fix, :+1: for the single 'a' resolution :)

**Comment by jordan-wright** [comment]
Going to go ahead and close this for now. @tyrells let me know if this fixes your issue as well. If not, we'll re-open.

Just remember to grab the latest source and rebuild before reproducing the issue.

Thanks for this report!

**Comment by tyrells** [comment]
Hi @jordan-wright. I have finally had a chance to check this and the bug still exists. 

I have had a better look at the code, and think the problem exists in the GetQueuedCampaigns() function, where the launch_date check is happening.

The format of launch_date in the database is somthing like '2016-10-17 10:13:00+02:00', where as the string representation in the golang Time parameter 't' is similar to '2016-10-17 04:58:19.258849297 -0400 EDT' - assuming different timezones.

I think the problem is that since sqlite doesn't have a specific datetime data type, a string comparison is actually taking place when these 2 values are compared. This could probably be fixed by using the golang Time.Format() function to return a specific string representation of the current time, and then the builtin sqlite datetime() function to wrap both dates and do a proper datetime comparison.

**Comment by ryan-es2** [comment]
I believe I am experiencing this very issue right now, how do I verify or fix this ? I have a clean install on a 16.10 box Thanks :)

**Comment by tyrells** [comment]
Hi @ryan-es2, a workaround would be to change the timezone of the server to the same timezone as your browser. Otherwise you may want to have a look at the datetime formats I mentioned in my post above and play around with those.

**Comment by ryan-es2** [comment]
Thanks @tyrells I tried changing my campaign time to match the server without success haha :) just googling now how to change the server timezone via terminal

**Comment by packetflare** [comment]
Confirm the issue still exists. Server must be in UTC, but clients are spread around the globe, so this introduces a usability problem

**Comment by ryan-es2** [comment]
rm /etc/localtime
ln -s /usr/share/zoneinfo/your_zone /etc/localtime
date

**Comment by jeffers102** [comment]
In my case, the server is set to UTC.  I solved this scheduling problem by always saving LaunchDate (or any date) in UTC.  So, in PostCampaign, prior to INSERTING, I just added the following:

c.LaunchDate = c.LaunchDate.UTC()

It would be nice if SQLite handled comparisons with different timezones itself, but in my case, saving to UTC was going to happen anyways and it fixes this issue.

**Comment by jordan-wright** [comment]
Hey everyone, just giving an update on this one. This is one of the top priorities, atm.

The way I'm going to address it is to introduce a schema migration that converts all existing dates to UTC. Then, any new campaigns will be also stored at UTC.

Finally, I'll make changes in the frontend to render the UTC dates using the browser's local time so dates are easy to read.

This does mean that the API will be returning UTC dates instead of dates with local time. I don't anticipate this to cause much issues, since most libraries should just be parsing dates as is, but it's something to be aware of.

Sorry for all the hassle this has caused!

**Comment by jordan-wright** [comment]
Ok everyone, I've taken a shot at fixing this one. A couple of notes:

This adds a db migration, so you may wish to consider backing up your database. Shouldn't be anything we can't fix if things go wrong (we're just adjusting timezones) but it might help 🤷‍♂️ 

Also, if you're using MySQL, you'll want to change your connect string from `loc=Local` to `loc=UTC`. I've already updated the docs to reflect this.

Other than that, all dates will now be stored as UTC. This should fix the issue of having different timezones, but if someone can confirm, it'd be appreciated!
